server:
    port: 8000

spring:
#mysql
    mvc:
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/fileblocker?serverTimezone=Asia/Seoul
        username: angel
        password: 1234
#mybatis
mybatis:
    type-aliases-package: com.fileblocker.flow
    mapper-locations:
    - /mapper/*.xml
